{% set name = "motifcluster" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0a980542648ed8db4112c922eab1a6a4319d9f8eac92643bf2c52421b08bc57a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - networkx >=2.4
    - numpy >=1.18.3
    - python >=3.5
    - scikit-learn >=0.22.2
    - scipy >=1.4.1

test:
  imports:
    - motifcluster

about:
  home: https://github.com/WGUNDERWOOD/motifcluster
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: Motif-Based Spectral Clustering of Weighted Directed Networks
  doc_url: https://motifcluster.readthedocs.io
  dev_url: https://github.com/WGUNDERWOOD/motifcluster

extra:
  recipe-maintainers:
    - WGUNDERWOOD
