{% set name = "motifcluster" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0bf311631c61c6fb1ab0040a414b438c997b2c3b33e8eab30d7b159bfa3263c6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - networkx >=2.4
    - numpy >=1.18.3
    - python >=3.5
    - scikit-learn >=0.22.2
    - scipy >=1.4.1

test:
  imports:
    - motifcluster

about:
  home: https://github.com/WGUNDERWOOD/motifcluster
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: Motif-Based Spectral Clustering of Weighted Directed Networks
  doc_url: https://motifcluster.readthedocs.io
  dev_url: https://github.com/WGUNDERWOOD/motifcluster

extra:
  recipe-maintainers:
    - WGUNDERWOOD
